### ISSUE TITLE
HashMap expand crash

### ISSUE THREAD

**Issue by clienthax** [stanhebben/MineTweaker#12]
http://pastebin.ubuntu.com/7236297/

**Comment by clienthax** [comment]
seems to be very hit and miss to when i get the crash, guessing its the hashmap implementation itself

**Comment by stanhebben** [comment]
A tiny little bug in the hashmap implementation. Been using it a long time but never noticed it. Thanks for reporting! It's been fixed, I will roll out a new version with some bugfixes soon.

**Comment by clienthax** [comment]
@stanhebben has the fix been pushed tp the github yet?, im managing to trigure it 1/3 times each mod pack launch ;)

**Comment by stanhebben** [comment]
It's been pushed. But I couldn't build it yet on my PC due to incompatibilities between some of the mod versions I happen to have at the moment... see if you can get it built.

**Comment by clienthax** [comment]
im having trouble with gregtech api trying to hook into the ue core files (not in the ue api for some freking reason), while compiling,
could you upload the api's you used to compile it ?
