### ISSUE TITLE
Gregtech support broken

### ISSUE THREAD

**Issue by ghost** [stanhebben/MineTweaker#18]
Whenever I try to use import mods.gregtech, I get an invalid expression in the chat. Here is some example code I'm trying to use:
# Cheaper Rails

import mods.gregtech.Assembler;

var rails = minecraft:rail;
var woodbed = Railcraft:part.railbed;
var stonebed = Railcraft:part.railbed:1;
var stonerail = Railcraft:part.rail;
var rerail = Railcraft:part.rail:4;
var hsrail = Railcraft:part.rail:3;
var refrails = Railcraft:tile.railcraft.track:24050.withTag({track:"railcraft:track.reinforced"});
var speedrails = Railcraft:tile.railcraft.track:816.withTag({track:"railcraft:track.speed"});

recipes.remove(rails);
recipes.remove(refrails);
recipes.remove(speedrails);

Assembler.remove(rails);
Assembler.remove(refrails);
Assembler.remove(speedrails);

recipes.addShaped(rails \* 4,
 [[ore:nuggetIron, null, ore:nuggetIron],
  [ore:nuggetIron, minecraft:stick, ore:nuggetIron],
  [ore:nuggetIron, null, ore:nuggetIron]]);

recipes.addShaped(rails\* 64,
 [[stonerail, null, stonerail],
  [stonerail, woodbed, stonerail],
  [stonerail, null, stonerail]]);

Assembler.addRecipe(rails \* 64, woodbed, stonerail \* 6, 20, 1);

recipes.addShaped(refrails \* 64,
  [[rerail, null, rerail],
   [rerail, stonebed, rerail],
   [rerail, null, rerail]]);

Assembler.addRecipes(refrails \* 64, stonebed, rerail \* 6, 20, 1);

recipes.addShaped(speedrails \* 64,
 [[hsrail, null, hsrail],
  [hsrail, stonebed, hsrail],
  [hsrail, null, hsrail]]);

Assembler.addRecipes(speedrails \* 64, stonebed, hsrail \* 6, 20, 1);

**Comment by stanhebben** [comment]
You're on the wrong issue tracker. This one is for MT2, find the new one at https://github.com/stanhebben/MineTweaker3/issues
