### ISSUE TITLE
[Question] [Possible Feature Request] Is this possible? 

### ISSUE THREAD

**Issue by SnowShock35** [stanhebben/MineTweaker#21]
Hi Stan,

I am back with another question for you, hope you don't mind too much.
So my question is... Is it possible to import values from another minetweaker script so I don't have to write them in each script almost like having a dictionary, if this isn't could it possibly have it as a feature would be really nice to specify all values in a separate script and then import them using the same method as you do with the NEI mod integration (import mods.nei.NEI;).

Anyways thought I would just ask as I really liked being able to do that in MT 2. But let me know. Thanks.
-Snow :)

**Comment by stanhebben** [comment]
Don't worry, it's planned for MineTweaker 3.1 :)

**Comment by SnowShock35** [comment]
Nice! thank you very much. Any sort of ETA on that or still gonna be in dev for a while?
