### ISSUE TITLE
[QUESTION] Getting an ItemStack from a wildcard

### ISSUE THREAD

**Issue by MikeBurk** [stanhebben/MineTweaker#24]
This may be a user error, or may not be implemented...

I was trying:
val seat = ore:seat;
seat.addAll(BiblioCraft:BiblioSeats:*);

The idea being to use the wildcard to get all of the items with that id and assign them to the new oreDict value.  It seems like the wildcard is not actually returning me an ItemStack to work with addAll.  I tried just add, but only works if I call out each meta id (or 0 by default if I do none).

Is this a user error or is something not intuitive about addAll?  Thanks.

**Comment by stanhebben** [comment]
You're posting in the wrong project (this is the old MineTweaker, the new one is at https://github.com/stanhebben/MineTweaker3)

The add method is the right one, I will have check out why it doesn't work. Which minecraft version are you using?

**Comment by MikeBurk** [comment]
My apologies!

I am moving it to the other repro and reproducing again.
