### ISSUE TITLE
Recipe removal quirk

### ISSUE THREAD

**Issue by PitchBright** [stanhebben/MineTweaker#32]
If I do this:

recipes.addShapeless(minecraft:dye:0 \* 4, [minecraft:bone, minecraft:coal:1, Metallurgy:tar, Aquaculture:item.Fish:*, minecraft:potion:0.transformReplace(minecraft:glass_bottle)]);

recipes.removeShapeless(minecraft:dye:0, [minecraft:bone, minecraft:coal:1, Metallurgy:tar, Aquaculture:item.Fish:13, minecraft:potion:0]);

I'm expecting Aquaculture:item.Fish:13 to be removed from the original recipe, leaving all the other Aquaculture:item.Fish:\* in full effect… but Aquaculture:item.Fish:13 remains in the recipe for some reason.

Or am I doing it wrong?

**Comment by copygirl** [comment]
You are indeed doing it wrong. What you're doing is trying to remove a specific recipe (of which there is _only one_, not one per type of fish - the way you've done it) which contains `Aquaculture:item.Fish:13` in its ingredients.

Fortunately there's two ways (that I can think of) to do this: Either add separate recipes for each type of fish or creating a new ore dictionary entry (for example "anyFish", or "aquacultureFish") and then creating a single recipe. No, you're not going to have to do this manually:

#### Setup

```
import minetweaker.item.IItemStack;
var allFish = [
    <Aquaculture:item.Fish:0>,
    <Aquaculture:item.Fish:1>,
    <Aquaculture:item.Fish:2>,
    <Aquaculture:item.Fish:3>,
    ...
    <Aquaculture:item.Fish:12>,
    <Aquaculture:item.Fish:14>,
    <Aquaculture:item.Fish:15>
  ] as IItemStack[];
```

#### Option 1

```
var anyFish = <ore:anyFish>; // This creates a new ore dictionary entry.
for i, fish in allFish { // Go through everything in the list of fish.
  anyFish.add(fish); // Add each fish to the ore dictionary entry.
}
// Now create a recipe using "anyFish" or "<ore:anyFish>".
```

#### Option 2

```
for i, fish in allFish { // Go through everything in the list of fish.
  // Create a recipe using "fish" as an ingredient.
}
```

Not sure if it's possible to make a traditional for loop, it might decrease the number of lines needed. Though this is a pretty general example which can be applied to make all kinds of neat things. For example I used it to make recipes that [increase the plank / stick output when crafting an axe with logs / planks.](https://gist.github.com/copygirl/f4e9dfebdf51f29c28a4)

**Comment by PitchBright** [comment]
Thanks! You rock, copygirl!
